### ISSUE TITLE
Feature: Read OSM protobuf

### ISSUE THREAD

**Issue by paulkoehlerdev** [paulkoehlerdev/gosmRoutify#1]
## Description

OSM data is provided in the `.osm.pbf` Protobuf format by Geofabrik. We want to be able to read those files.

## TODO

- [x] Create Protobuf Mappings
- [x] Create Scanner for Continuus File Scanning
- [x] Create Tests
- [x] Create a Service Wrapping this Library
