### ISSUE TITLE
Feature: Create a simple Map frontend

### ISSUE THREAD

**Issue by paulkoehlerdev** [paulkoehlerdev/gosmRoutify#5]
## TODO

- [x] Create a frontend
- [x] Host it with the project
- [x] Create a api endpoint for routing
- [x] Return some mock geojson for testing
